### PR TITLE
Be more flexible in finding reference data, update to match current Galaxy .ga format

### PR DESCRIPTION
**Pull request by pvanheus**
This PR aims to address the problem reported in #4. The bug was triggered by the workflow that I am working on (https://github.com/pvanheus/irida-pipeline-plugins/tree/sample_0.3.0/snippy-tb-sample-iqtree).

### CODE REVIEW

**Comment by pvanheus** [comment]
Currently a run of `irida-wf-ga2xml` with this patch still gives errors, but not fatal ones:

```
$ lein run project.clj -n 'MTuberculosisPhylogeny' -t SNIPPY_PHYLOGENOMICS -W 0.1.4 --input irida_workflow_structure.ga --outdir output |&tee out.log
21-01-19 11:37:49 world ERROR [irida-wf-ga2xml.messages:174] - Could not get tool parameter attribute info for {:name "tb_variant_filter", :owner "iuc", :url "https://toolshed.g2.bx.psu.edu", :revision "3b1e7c170b10"} ; Encountered error: java.lang.IllegalArgumentException: Arg 'kw' is not a Clojure Keyword! class=
21-01-19 11:37:53 world ERROR [irida-wf-ga2xml.messages:174] - Could not get tool parameter attribute info for {:name "vcf_to_alignment", :owner "sanbi-uwc", :url "https://testtoolshed.g2.bx.psu.edu", :revision "4f3f7d390382"} ; Encountered error: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[2,1]
Message: Content is not allowed in prolog.
21-01-19 11:37:54 world ERROR [irida-wf-ga2xml.messages:174] - Could not get tool parameter attribute info for {:name "snp_sites", :owner "iuc", :url "https://toolshed.g2.bx.psu.edu", :revision "5804f786060d"} ; Encountered error: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[2,1]
Message: Content is not allowed in prolog.
21-01-19 11:37:56 world ERROR [irida-wf-ga2xml.messages:174] - Could not get tool parameter attribute info for {:name "snp_sites", :owner "iuc", :url "https://toolshed.g2.bx.psu.edu", :revision "5804f786060d"} ; Encountered error: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[2,1]
Message: Content is not allowed in prolog.
21-01-19 11:37:59 world ERROR [irida-wf-ga2xml.messages:174] - Could not get tool parameter attribute info for {:name "snp_dists", :owner "iuc", :url "https://toolshed.g2.bx.psu.edu", :revision "1959cc43b414"} ; Encountered error: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[2,1]
Message: Content is not allowed in prolog.
21-01-19 11:37:59 world ERROR [irida-wf-ga2xml.messages:174] - Could not get tool parameter attribute info for {} ; Encountered error: java.io.FileNotFoundException: /repos/file (No such file or directory)
21-01-19 11:38:02 world ERROR [irida-wf-ga2xml.messages:174] - Could not get tool parameter attribute info for {:name "iqtree", :owner "iuc", :url "https://toolshed.g2.bx.psu.edu", :revision "d1c340a5664b"} ; Encountered error: java.lang.IllegalArgumentException: Arg 'kw' is not a Clojure Keyword! class=
```

The workflow imports into IRIDA but at runtime triggers another error when submitting to Galaxy:

```
19 Jan 2021 11:50:16,681 ERROR ca.corefacility.bioinformatics.irida.service.analysis.execution.AnalysisExecutionServiceAspect:65 - Error occured for submission: AnalysisSubmission [id=38, name=MTuberculosisPhylogeny_20210119_SRR12416825, submitter=admin, workflowId=21e37691-cf1f-46ec-b07e-44ce44051957, analysisState=SUBMITTING, analysisCleanedState=NOT_CLEANED] changing to state ERROR
ca.corefacility.bioinformatics.irida.exceptions.WorkflowException: Cannot find workflowInputId for input label 
	at ca.corefacility.bioinformatics.irida.pipeline.upload.galaxy.GalaxyWorkflowService.getWorkflowInputId(GalaxyWorkflowService.java:88)
	at ca.corefacility.bioinformatics.irida.service.analysis.workspace.galaxy.AnalysisWorkspaceServiceGalaxy.prepareAnalysisFiles(AnalysisWorkspaceServiceGalaxy.java:228)
	at ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxyAsync.executeAnalysis(AnalysisExecutionServiceGalaxyAsync.java:147)
	at ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxyAsync$$FastClassBySpringCGLIB$$fc2d896.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at ca.corefacility.bioinformatics.irida.service.analysis.annotations.RunAsUserAspect.setSecurityContextFromAnalysisSubmission(RunAsUserAspect.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.security.concurrent.DelegatingSecurityContextCallable.call(DelegatingSecurityContextCallable.java:87)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
19 Jan 2021 11:50:16,683 ERROR ca.corefacility.bioinformatics.irida.service.analysis.execution.AnalysisExecutionServiceAspect:65 - Error occured for submission: AnalysisSubmission [id=37, name=MTuberculosisPhylogeny_20210119_SRR12416831, submitter=admin, workflowId=21e37691-cf1f-46ec-b07e-44ce44051957, analysisState=SUBMITTING, analysisCleanedState=NOT_CLEANED] changing to state ERROR
ca.corefacility.bioinformatics.irida.exceptions.WorkflowException: Cannot find workflowInputId for input label 
	at ca.corefacility.bioinformatics.irida.pipeline.upload.galaxy.GalaxyWorkflowService.getWorkflowInputId(GalaxyWorkflowService.java:88)
	at ca.corefacility.bioinformatics.irida.service.analysis.workspace.galaxy.AnalysisWorkspaceServiceGalaxy.prepareAnalysisFiles(AnalysisWorkspaceServiceGalaxy.java:228)
	at ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxyAsync.executeAnalysis(AnalysisExecutionServiceGalaxyAsync.java:147)
	at ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxyAsync$$FastClassBySpringCGLIB$$fc2d896.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at ca.corefacility.bioinformatics.irida.service.analysis.annotations.RunAsUserAspect.setSecurityContextFromAnalysisSubmission(RunAsUserAspect.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.security.concurrent.DelegatingSecurityContextCallable.call(DelegatingSecurityContextCallable.java:87)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

which in turn comes from https://github.com/phac-nml/irida/blob/development/src/main/java/ca/corefacility/bioinformatics/irida/pipeline/upload/galaxy/GalaxyWorkflowService.java#L88, where it looks like the `getWorkflowInputId()` method was called with an empty `workflowInputLabel`.

My debugging continues.

**Comment by pvanheus** [comment]
BTW there's a SSL certificate problem with Java reading the `https://irida.corefacility.ca/galaxy-shed` webpage. I wrote a `slurp-nocheck-sslcert` function to fetch webpages without checking the SSL cert, which gets around this problem.

**Comment by pvanheus** [comment]
The test suite has a strange problem where sometimes the test involving `flash-repo-info` fails, but otherwise the latest version of this PR seems to be working.

**Comment by JeffreyThiessen** [comment]
I've taken a quick look through the changes and these parsing flexibility changes look great.

I don't really feel comfortable with ignoring SSL certificates though. I haven't been able to reproduce the SSL cert problem you have, and from what I can see our corefacility.ca cert from Entrust is still working. I'm not sure if this is a localized problem for you or something else is going on that I can't replicate, but you may just want to have a fork with the SSL change for now.

A thing to note is that in the coming months we plan on getting rid of the https://irida.corefacility.ca/galaxy-shed toolshed, so if it's only the corefacility domain that you are having issue with then this will "fix itself" when it goes away.

**Comment by pvanheus** [comment]
@JeffreyThiessen I tested from my machine with Java and get the same SSL error. Demo code [here](https://github.com/pvanheus/irida_java_ssl_test).

In my latest update I ignore SSL errors *only* for `irida.corefacility.ca`.

**Comment by JeffreyThiessen** [comment]
This looks great. Thanks again for putting time into this!

**Pull request merged**
