### PR TITLE
IRIDA compatible directory output with messages_en.properties and proper filenames

### PR DESCRIPTION
**Pull request by peterk87**
- Added output directory cmdline opt for creating expected IRIDA workflow directory structure with `messages_en.properties`, `irida_workflow.xml`, and `irida_workflow_structure.ga`
- Extracting tool parameter labels from Galaxy tool XMLs for writing to messages file
- Optional extra attributes can be written to `toolParameter` tags in XML output from Galaxy tool XMLs 

### Files:
- [irida-wf-ga2xml-1.0.0-SNAPSHOT-standalone.zip](https://github.com/phac-nml/irida-wf-ga2xml/files/2284691/irida-wf-ga2xml-1.0.0-SNAPSHOT-standalone.zip) contains the compiled standalone jar at 6941c16b4b47f9b3f2bc52c7888367b40d5e20fc
- [SNVPhyl.zip](https://github.com/phac-nml/irida-wf-ga2xml/files/2284684/SNVPhyl.zip) contains the output directory from running `irida-wf-ga2xml` on the SNVPhyl Galaxy workflow v1.0.1 `*.ga` file. 
- [biohansel.zip](https://github.com/phac-nml/irida-wf-ga2xml/files/2276058/biohansel.zip) contains the `biohansel.ga` file for the `biohansel` example below
- [asm_annt.zip](https://github.com/phac-nml/irida-wf-ga2xml/files/2276062/asm_annt.zip) contains the `asm_annt.ga` file for the `AssemblyAnnotation` example below

### Example usage:

Basic pipeline:

```
$ java -jar irida-wf-ga2xml.jar -t biohansel -W 2.0.0 -i biohansel.ga -n biohansel -o /tmp

Wrote workflow XML to  /tmp/biohansel/2.0.0/irida_workflow.xml
Wrote Galaxy workflow *.ga file to  /tmp/biohansel/2.0.0/irida_workflow_structure.ga
Wrote IRIDA messages to  /tmp/biohansel/2.0.0/messages_en.properties
```

Contents of  `/tmp/biohansel/2.0.0/messages_en.properties`:
```properties
#Pipeline Info Properties
#Mon Aug 13 15:57:37 CDT 2018
pipeline.parameters.modal-title.biohansel=biohansel Pipeline Parameters
workflow.biohansel.description=
pipeline.h1.biohansel=biohansel Pipeline
pipeline.title.biohansel=Pipelines - biohansel
workflow.biohansel.title=biohansel Pipeline
#Tool Parameters - Tool: bio_hansel - Workflow Step #: 1
#Mon Aug 13 15:57:37 CDT 2018
pipeline.parameters.biohansel.bio_hansel-1-dev_args.use_json=Output JSON results
pipeline.parameters.biohansel.bio_hansel-1-qc_vals.max_intermediate_tiles=QC\: Decimal Proportion of max allowed missing tiles for an intermediate subtype
pipeline.parameters.biohansel.bio_hansel-1-qc_vals.min_ambiguous_tiles=QC\: Min number of tiles missing for Ambiguous Result
pipeline.parameters.biohansel.bio_hansel-1-kmer_vals.kmer_min=Min k-mer frequency/coverage
pipeline.parameters.biohansel.bio_hansel-1-qc_vals.max_missing_tiles=QC\: Decimal Proportion of max allowed missing tiles
pipeline.parameters.biohansel.bio_hansel-1-qc_vals.low_coverage_warning=QC\: Overall tile coverage below this value will trigger a low coverage warning
pipeline.parameters.biohansel.bio_hansel-1-kmer_vals.kmer_max=Max k-mer frequency/coverage
pipeline.parameters.biohansel.bio_hansel-1-qc_vals.low_cov_depth_freq=QC\: Frequency below this coverage are considered low coverage
pipeline.parameters.biohansel.bio_hansel-1-type_of_scheme.scheme_type=Specify scheme to use. (Heidelberg is default)
```

Pipeline with a few steps:

```
$ java -jar irida-wf-ga2xml.jar -t assembly -W 1.0.0 -i asm_annt.ga -n AssemblyAnnotation -o /tmp

Wrote workflow XML to  /tmp/AssemblyAnnotation/1.0.0/irida_workflow.xml
Wrote Galaxy workflow *.ga file to  /tmp/AssemblyAnnotation/1.0.0/irida_workflow_structure.ga
Wrote IRIDA messages to  /tmp/AssemblyAnnotation/1.0.0/messages_en.properties
```

Contents of `/tmp/AssemblyAnnotation/1.0.0/messages_en.properties`
```properties
#Pipeline Info Properties
#Mon Aug 13 15:56:13 CDT 2018
pipeline.parameters.modal-title.AssemblyAnnotation=AssemblyAnnotation Pipeline Parameters
workflow.asm_annt.title=AssemblyAnnotation Pipeline
pipeline.h1.AssemblyAnnotation=AssemblyAnnotation Pipeline
pipeline.title.AssemblyAnnotation=Pipelines - AssemblyAnnotation
workflow.asm_annt.description=
#Tool Parameters - Tool: flash - Workflow Step #: 1
#Mon Aug 13 15:56:13 CDT 2018
pipeline.parameters.AssemblyAnnotation.flash-1-max_overlap=Maximum overlap
pipeline.parameters.AssemblyAnnotation.flash-1-min_overlap=Minimum overlap
#Tool Parameters - Tool: spades - Workflow Step #: 2
#Mon Aug 13 15:56:13 CDT 2018
pipeline.parameters.AssemblyAnnotation.spades-2-iontorrent=Libraries are IonTorrent reads?
pipeline.parameters.AssemblyAnnotation.spades-2-kmer_choice.auto_kmer_choice=Automatically choose k-mer values
pipeline.parameters.AssemblyAnnotation.spades-2-sc=Single-cell?
pipeline.parameters.AssemblyAnnotation.spades-2-onlyassembler=Run only assembly? (without read error correction)
pipeline.parameters.AssemblyAnnotation.spades-2-careful=Careful correction?
pipeline.parameters.AssemblyAnnotation.spades-2-cov.state=Coverage Cutoff
#Tool Parameters - Tool: regex_find_replace - Workflow Step #: 3
#Mon Aug 13 15:56:13 CDT 2018
pipeline.parameters.AssemblyAnnotation.regex_find_replace-3-field.value=
#Tool Parameters - Tool: filter_spades_repeats - Workflow Step #: 4
#Mon Aug 13 15:56:13 CDT 2018
pipeline.parameters.AssemblyAnnotation.filter_spades_repeats-4-keep_leftover=Print out a fasta file containing the discarded sequences?
pipeline.parameters.AssemblyAnnotation.filter_spades_repeats-4-len_cutoff=Length cut-off
pipeline.parameters.AssemblyAnnotation.filter_spades_repeats-4-print_summary=Print out a summary of all the results?
pipeline.parameters.AssemblyAnnotation.filter_spades_repeats-4-cov_cutoff=Coverage cut-off ratio
pipeline.parameters.AssemblyAnnotation.filter_spades_repeats-4-rep_cutoff=Repeat cut-off ratio
pipeline.parameters.AssemblyAnnotation.filter_spades_repeats-4-cov_len_cutoff=Length for average coverage calculation
#Tool Parameters - Tool: assemblystats - Workflow Step #: 5
#Mon Aug 13 15:56:13 CDT 2018
pipeline.parameters.AssemblyAnnotation.assemblystats-5-all_outputs=Return all output files
pipeline.parameters.AssemblyAnnotation.assemblystats-5-bucket=Output histogram with bin sizes\=1
#Tool Parameters - Tool: prokka - Workflow Step #: 6
#Mon Aug 13 15:56:13 CDT 2018
pipeline.parameters.AssemblyAnnotation.prokka-6-gffver=GFF version (--gffver)
pipeline.parameters.AssemblyAnnotation.prokka-6-evalue=Similarity e-value cut-off
pipeline.parameters.AssemblyAnnotation.prokka-6-metagenome=Improve gene predictions for highly fragmented genomes (--metagenome)
pipeline.parameters.AssemblyAnnotation.prokka-6-fast=Fast mode (--fast)
pipeline.parameters.AssemblyAnnotation.prokka-6-plasmid=Plasmid name or identifier (--plasmid)
pipeline.parameters.AssemblyAnnotation.prokka-6-species=Species name (--species)
pipeline.parameters.AssemblyAnnotation.prokka-6-compliant.compliant_select=Force GenBank/ENA/DDJB compliance (--compliant)
pipeline.parameters.AssemblyAnnotation.prokka-6-genus=Genus name (--genus)
pipeline.parameters.AssemblyAnnotation.prokka-6-norrna=Don't run rRNA search with Barrnap
pipeline.parameters.AssemblyAnnotation.prokka-6-increment=Locus tag counter increment (--increment)
pipeline.parameters.AssemblyAnnotation.prokka-6-centre=Sequencing centre ID (--centre)
pipeline.parameters.AssemblyAnnotation.prokka-6-kingdom.kingdom_select=Kingdom (--kingdom)
pipeline.parameters.AssemblyAnnotation.prokka-6-rfam=Enable searching for ncRNAs with Infernal+Rfam (SLOW\!) (--rfam)
pipeline.parameters.AssemblyAnnotation.prokka-6-notrna=Don't run tRNA search with Aragorn
pipeline.parameters.AssemblyAnnotation.prokka-6-usegenus=Use genus-specific BLAST database (--usegenus)
pipeline.parameters.AssemblyAnnotation.prokka-6-locustag=Locus tag prefix (--locustag)
pipeline.parameters.AssemblyAnnotation.prokka-6-strain=Strain name (--strain)
pipeline.parameters.AssemblyAnnotation.prokka-6-kingdom.gcode=Genetic code (transl_table)
```

### CODE REVIEW

**Comment by apetkau** [comment]
Thanks @peterk87. This looks amazing :smile:. It makes it really easy to generate the necessary files to integrate an IRIDA pipeline. I even got it working with my plugin pipelines code.

One general comment I had relates to the `#Tool Parameters - pipeline.parameters.biohansel.bio_hansel-1-type_of_scheme.scheme_type` comments in the `messages_en.properties` file.  Is this meant to be commented out?  It looks like the parameter name is a duplicate of one of the ones listed below.

**Comment by apetkau** [comment]
It looks like some entries in the `messages_en.properties` may also be missing.  For example for the assembly workflow I get the following in the *irida_workflow.xml* file:

```xml
<parameter name="regex_find_replace-3-field.value" defaultValue="3">
```

But, I get no corresponding entry for **regex_find_replace-3-field.value** in the `messages_en.properties` file.

**Comment by peterk87** [comment]
Thanks for taking a look at it and trying it out! That's great that it works with your pipeline plugin code.

> One general comment I had relates to the #Tool Parameters - pipeline.parameters.biohansel.bio_hansel-1-type_of_scheme.scheme_type comments in the messages_en.properties file. Is this meant to be commented out? It looks like the parameter name is a duplicate of one of the ones listed below.

The idea was to take the tool name and workflow step and write that to the comment for that group of tool parameter messages. I'll fix it up.

> But, I get no corresponding entry for regex_find_replace-3-field.value in the messages_en.properties file.

It looks like there is no param tag with name "value" under section or conditional tag "field" in https://toolshed.g2.bx.psu.edu/repository?repository_id=92f6346372afb197. I could have it setup to write blank messages for tool param properties that could not be retrieved.

Thanks for reporting these issues!

**Comment by peterk87** [comment]
Hey @apetkau,

As of 6941c16b4b47f9b3f2bc52c7888367b40d5e20fc, all tool param messages keys have a default value of `""` (empty string) so if a label value cannot be extracted then at least the key will show up in the `messages_en.properties` file. The comments highlighting the different tool step sections within the `messages_en.properties` should be more clear (e.g. `#Tool Parameters - pipeline.parameters.biohansel.bio_hansel-1-type_of_scheme.scheme_type` -> `#Tool Parameters - Tool: bio_hansel - Workflow Step #: 1`).

I've also added the option (`-x`/`--extra-tool-param-attrs`) to save some extra Galaxy tool param values to the XML (only label and type right now; the extra values don't seem to interfere with loading the XMLs within IRIDA, but more testing is required). The type attribute might be useful for IRIDA-side validation of input values before sending anything to Galaxy. The label attribute could be useful for workflows with a lot of steps and parameters since the param key name isn't always intuitive (e.g. FreeBayes: `parameterName="options_type.O" label="Turn off left-alignment of indels?"`).

Thanks again for taking a look at this update!

**Comment by apetkau** [comment]
Thanks Peter. This works out great. I can build and load pipelines in IRIDA from all three of those workflow files you uploaded.

I do have 2 additional comments:
1. If you name a pipeline with capital letters (e.g., `-n AssemblyAnnotation`), the name in the **messages_en.properties** file will use this same name with capitals (e.g., `pipeline.parameters.AssemblyAnnotation.flash-1-min_overlap=Minimum overlap`).  But, in IRIDA the **name** part here should be lower-case to properly load up the messages (e.g., `pipeline.parameters.assemblyannotation.flash-1-min_overlap=Minimum overlap`).  This is done in [this](https://github.com/phac-nml/irida/blob/development/src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java#L228) line of code in IRIDA (converting the workflow name to lower case, then using it to build the key for the **messages** file).
2. If a **message** is blank instead of making it empty I wonder if it would be more useful to make it equal to the key (e.g., `pipeline.parameters.snvphyl.samtools_mpileup-7-reference_source.reference_source_selector=samtools_mpileup-7-reference_source.reference_source_selector`?  That way you wouldn't have blank text boxes in the parameters if you tried to load up the workflow into IRIDA as-is:

    image

**Comment by peterk87** [comment]
Thanks for the comments @apetkau!

I'm in the process of making the changes you suggested, but I'm a little confused about when to preserve the case of the workflow name in the `messages.properties` key and when to make it lowercase. It looks like `pipeline.title.<WorkflowName>` and `pipeline.h1.<WorfklowName>` can have the case preserved (must have the case preserved?), e.g.

```
pipeline.title.SNVPhyl=Pipelines - Phylogenomics
pipeline.h1.SNVPhyl=SNVPhyl Phylogenomics Pipeline
...
pipeline.title.MLSTMentalist=MentaLiST MLST Pipeline
pipeline.h1.MLSTMentalist=MentaLiST MLST
```

But `pipeline.parameters.modal-title.<workflowname>` must have the workflow name in lowercase?

```
pipeline.parameters.modal-title.sistrtyping=SISTR Pipeline Parameters
pipeline.parameters.modal-title.refseqmasheronpairedreads=RefSeqMasher Parameters
pipeline.parameters.modal-title.snvphyl=SNVPhyl Pipeline Parameters
```

Is that correct?

**Comment by apetkau** [comment]
Yep Peter, this is correct. More specifically it's `pipeline.title.<AnalysisType>` and `pipeline.h1.<AnalysisType>` (from [here](https://github.com/phac-nml/irida/blob/development/src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java#L164)). The `AnalysisType` is defined in the workflow XML file at https://github.com/phac-nml/irida/blob/development/src/main/resources/ca/corefacility/bioinformatics/irida/model/enums/workflows/AssemblyAnnotation/0.4/irida_workflow.xml#L7.

The rest are `pipeline.parameters.modal-title.<workflowname>`, where `workflowname` is the lower-case version of the workflow name (defined in the XML file at https://github.com/phac-nml/irida/blob/development/src/main/resources/ca/corefacility/bioinformatics/irida/model/enums/workflows/AssemblyAnnotation/0.4/irida_workflow.xml#L5).

This is really something we should make consistent in IRIDA (I've made an issue at http://gitlab-irida.corefacility.ca/irida/irida/issues/670), but for now this tool should produce messages files that are compatible/consistent with what IRIDA does currently.

**Comment by peterk87** [comment]
@apetkau I can find `pipeline.(title|h1).<name>`, but not `pipeline.(title|h1).<analysisType>` (where `<name>` and `<analysisType>` are the values from the XML tags in the `irida_workflow.xml`) in the [`messages_en.properties` file](https://github.com/phac-nml/irida/blob/development/src/main/resources/i18n/messages_en.properties#L1406).

Also, are there any restrictions for allowed characters for the analysis type? Word characters and dashes only (e.g. `^[^\w\-]+`)?

Thanks!

**Comment by apetkau** [comment]
Woops, you're right. I was linking to the wrong thing.  There are three difference instances:
1. `pipeline.(title|h1).<WorkflowName>` (case left as is): defined in [IRIDA code](https://github.com/phac-nml/irida/blob/9a45a752cb8c7e61d23b2534f4581d155b16af3a/src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java#L328), used in [messages_en.properties](https://github.com/phac-nml/irida/blob/9a45a752cb8c7e61d23b2534f4581d155b16af3a/src/main/resources/i18n/messages_en.properties#L1406) (`pipeline.title.SNVPhyl`)
2. `workflow.<AnalysisType>.(title|description)` (case left as is): defined in [IRIDA code](https://github.com/phac-nml/irida/blob/9a45a752cb8c7e61d23b2534f4581d155b16af3a/src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java#L165), used in [messages_en.properties](https://github.com/phac-nml/irida/blob/9a45a752cb8c7e61d23b2534f4581d155b16af3a/src/main/resources/i18n/messages_en.properties#L1444) (`workflow.phylogenomics.title`)
3. `pipeline.parameters.modal-title.<workflowname>.*` (lower-case): defined in [IRIDA code](https://github.com/phac-nml/irida/blob/9a45a752cb8c7e61d23b2534f4581d155b16af3a/src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java#L228), used in [messages_en.properties](https://github.com/phac-nml/irida/blob/9a45a752cb8c7e61d23b2534f4581d155b16af3a/src/main/resources/i18n/messages_en.properties#L1423) (`pipeline.parameters.modal-title.snvphyl`)

**Comment by apetkau** [comment]
And there are no character restrictions for the analysis type (though I would imagine whitespace could cause issues).

**Comment by peterk87** [comment]
Thanks for the clarification! 

I've made some changes to adhere with the expected formatting of Properties file key names in 007c31c47ccaa957eb5c52b5f88be4eaec7ea317

I've also changed the default tool param `messages.properties` value to be the tool name, workflow step and tool param key (e.g. `<keyname>=prokka-10-genus`)

Here's the jar at 007c31c47ccaa957eb5c52b5f88be4eaec7ea317: 
[irida-wf-ga2xml-1.0.0-SNAPSHOT-standalone.zip](https://github.com/phac-nml/irida-wf-ga2xml/files/2288226/irida-wf-ga2xml-1.0.0-SNAPSHOT-standalone.zip)

**Comment by apetkau** [comment]
Thanks Peter. This works great now.  I'm merging it in.

**Pull request merged**
